### ISSUE TITLE
Extension:DarkMode PoC

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#202]
https://www.mediawiki.org/wiki/Extension:DarkMode

**Comment by lens0021** [comment]
![image](https://user-images.githubusercontent.com/28209361/86123465-83036800-bb14-11ea-9dbb-a2329a2c4fd5.png)

```css
html.darkmode body {
    background: white;
}
```
위 코드만 추가해서 쓰면 보기에는 괜찮습니다. 다만 experimental 라서 그런지 활성화 하고 화면 이동하면 바로 꺼지는 등 정상적인 사용이 가능해 보이진 않습니다.
