### ISSUE TITLE
다크모드 배경색이 바뀌지 않음

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#324]
![Screenshot_20221231-101527](https://user-images.githubusercontent.com/28209361/210120733-8e35bee6-ea83-409c-85bb-5805f4180aad.png)

**Comment by lens0021** [comment]
파이어폭스는 이 코드로 인해 영향이 없습니다
```css
/* Hacks for older Firefox versions */
@-moz-document url-prefix() {
	body {
		background: #000;
	}
}

@-moz-document url-prefix() {
	@supports (overflow-clip-margin: 1px) {
		body {
			background: #fff;
		}
	}
}
```
https://github.com/wikimedia/mediawiki-extensions-DarkMode/blob/cff00a73ea41ee5d7de2cdad1e6b5f67f2b5180b/resources/ext.DarkMode.less#L197-L210
